name: NoodlesBowl
version: 1.0.9
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^1.2.1
  animated_bottom_navigation_bar: ^1.2.0
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  lottie: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  expansion_tile_card: ^3.0.0
  bottom_bar: ^2.0.2
  rflutter_alert: ^2.0.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  connectivity:
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
#  flutter_local_notifications: ^17.1.0
  flutter_local_notifications: ^9.5.3+1
  flutter_launcher_icons: ^0.13.0
  google_maps_flutter: ^2.2.5
  location: ^6.0.1
  geolocator: ^9.0.2
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.1.10
  map_launcher: ^3.3.0
  webview_flutter: ^4.0.7
  google_api_headers: ^2.0.3
  flutter_html: any

  flutter: 
    sdk: flutter
#platforms:
#  windows:
#    default_package: google_api_headers



dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter
#dependency_overrides:
#  google_api_headers: ^1.3.0-dev.0

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "ic_launcher"
  ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
